### ISSUE TITLE
bug(demux sheet fetch on hasta)

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/demultiplexing#128]
Demux fetch sheet is not working properly on hasta due to missing file:

```shell
[12|90|676] [hiseq.clinical@hasta:~] [P_main] 1 $ demux sheet fetch -a nova HVKJCDRXX
Traceback (most recent call last):
  File "${P_demux_path}/bin/demux", line 10, in <module>
    sys.exit(demux())
  File "${P_demux_path}/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "${P_demux_path}/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "${P_demux_path}/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "${P_demux_path}/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "${P_demux_path}/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "${P_demux_path}/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "${P_demux_path}/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "${P_demux_path}/lib/python3.7/site-packages/demux/cli/samplesheet.py", line 173, in fetch
    with open(f"{dir_path}/../../files/20181012_Indices.csv") as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: '${P_demux_path}/lib/python3.7/site-packages/demux/cli/../../files/20181012_Indices.csv'
```

Fix:
- [ ] Place said said in proper place

@barrystokman any reason this file could have been removed?

**Comment by barrystokman** [comment]
It's not removed, this was never meant to be run on hasta. The solution for now is to run this command on thalamus. A more robust solution is incoming.

**Comment by henrikstranneheim** [comment]
Solved by https://github.com/Clinical-Genomics/demultiplexing/pull/134
